### ISSUE TITLE
Responsive  Design Bug 1) Input bar 2) Links to Other Page 3) Wrong  Title Color

### ISSUE THREAD

**Issue by jieunkxx** [czhaoca/TheKimsPlusTwo#19]
Input bar disappears on Home page when window size shrinks

**Comment by notpritam** [comment]
can you please assign this to me , i would love to work on this.

**Comment by jieunkxx** [comment]
@notpritam This is an academic team project for a course assignment. Not an open project to public

**Comment by notpritam** [comment]
Oh sorry bro, i was searching for some projects to work with people
together,
Came accross this one, didn't knew that it is a team project...
