### ISSUE TITLE
Implement user interface for searching and filtering through listings.

### ISSUE THREAD

**Issue by czhaoca** [czhaoca/TheKimsPlusTwo#2]
- [x] #9 
- [x] #13 
- [x] #11

**Comment by redaoutamra** [comment]
can you asign me this ?

**Comment by czhaoca** [comment]
@redaoutamra 
Thank you for your interest in our project. However, this project is a part of our school coursework and, due to academic guidelines, we are only able to accept contributions from enrolled students. We appreciate your understanding and look forward to potential collaborations in the future.
