### ISSUE TITLE
Collecting available API.

### ISSUE THREAD

**Issue by czhaoca** [czhaoca/TheKimsPlusTwo#31]
Zillow API data knowledge dump.

**Comment by pukkuKim** [comment]
/property
/images
/priceAndTaxHistory
/rentEstimate
/walkAndTransitScore
/similarProperty

are among what I find useful from the Zillow.com API list.

**Comment by chohyeonkim** [comment]
Useful
/property (Property details) : `Detailed page`
/images (Property images and videos) : `Detailed page`
/building (Building details) : `Detailed page`

/priceAndTaxHistory (Price & Tax History) : ` History Page`  (Real)
/zestimateHistory (Zestimate History) : ` History Page`  (Estimate)

/propertyExtendedSearch : Very useful for `Search Option` , `Home Page`
(Could use /propertyByCoordinate, /locationSuggestions , /searchByUrl (List of properties by url))

/similarProperty , /similarSales(Sold)  : Could use this to recommend other houses or `Compare Page`
/propertyComps (Property comps) : Comparable Sales  `Compare Page`

/similarForRent , /rentEstimate  : if Only we deal with Rent (zpid or property_url require)

Potentially?
 /resolveAddressToZpid  : Could use address  to find Zpid

/walkAndTransitScore : extra feature? 

???
GET / Remove JobNumber : Not sure what JobNumber is?
Build Web Url.

**Comment by czhaoca** [comment]
Endpoint:	/property (Property details)
Use:		Getting property unique ID (zpid) for further processing

Endpoint:	/images (Property images and videos)
Usage:		Getting property’s images given zpid

Endpoint:	/priceAndTaxHistory (Price & Tax History)
Usage:		(using zpid) Feeding PropertyCards with price, feeding details page with tax info. Tax history is optional

Endpoint:	/propertyComps (Property comps)
Usage:		Pending for discovery

Endpoint:	/propertyByMls (Search by MLS # )
Usage:		low usage, getting zpid with MLS #

Endpoint:	/rentEstimate (Rent estimate)
Usage:		Feeding details page with rent estimation (using query such as address)

Endpoint:	/walkAndTransitScore (Walk, Bike and Transit scores)
Usage:		Feeding details page with rent estimation (using zpid)

Endpoint:	/building (Building details)
Usage:		Using lotID to get details from the building

Endpoint:	/zestimateHistory (Zestimate History)
Usage:		Feeding details page with rent estimation (using zpid)

**Comment by czhaoca** [comment]
Please click 👍 if we can close this issue @jieunkxx @chris718 @chohyeonkim @pukkuKim
