### ISSUE TITLE
Data Design for User Profile + Likes Pages

### ISSUE THREAD

**Issue by pukkuKim** [czhaoca/TheKimsPlusTwo#33]
**Left Column:**
1. UserCard (upper box):
- loggedInUser.profilePic
- loggedInUser.firstName
2. UserInfo (lower box):
- loggedInUser.firstName
- loggedInUser.lastName
- loggedInUser.age
- loggedInUser.emailAddress
- loggedInUser.phoneNumber
- loggedInUser.region

**Right Column OR Likes Page:**
- loggedInUser.likedProperties

**Comment by czhaoca** [comment]
I've moved your design to:
https://github.com/czhaoca/TheKimsPlusTwo/wiki/Data-Design-for-User-Profile---Like-Pages
This will help us to preserve your precious design after the issue has been closed :)
