### ISSUE TITLE
Data Design for Home Page with Search Option

### ISSUE THREAD

**Issue by chohyeonkim** [czhaoca/TheKimsPlusTwo#34]
![image](https://github.com/czhaoca/TheKimsPlusTwo/assets/104462860/c0cd3b60-559d-4c8d-ab21-562d33e83108)

![image](https://github.com/czhaoca/TheKimsPlusTwo/assets/104462860/aaa97f6f-4ed1-4f4f-870b-a06862427f74)

**RawData from PropertyExtendedSearch (each object has 24 keys or 25 keys )**

{
"props": [
    {
      "dateSold": null,
      "propertyType": "TOWNHOUSE",
      "lotAreaValue": null,
      "address": "1459 SE Columbia Way, Vancouver, WA 98661",
      "variableData": {
        "text": "$50,000 (Jun 13)",
        "type": "PRICE_REDUCTION"
      },
      "priceChange": -50000,
      "zestimate": 1366666,
      "imgSrc": "https://photos.zillowstatic.com/fp/cc0b58f51fa6fa30bd5a23d3118b1d06-p_e.jpg",
      "price": 1400000,
      "bedrooms": 3,
      "contingentListingType": null,
      "longitude": -122.655464,
      "latitude": 45.6176,
      "listingStatus": "FOR_SALE",
      "zpid": "23237157",
      "listingSubType": {
        "is_FSBA": true
      },
      "rentZestimate": 6474,
      "daysOnZillow": -1,
      "bathrooms": 3,
      "livingArea": 1666,
      "country": "USA",
      "currency": "USD",
      "lotAreaUnit": null,
      "hasImage": true
    },
    {
      "dateSold": null,
      "propertyType": "TOWNHOUSE",
      "lotAreaValue": 3049.2,
      "address": "11129 NE 43rd Cir, Vancouver, WA 98682",
      "variableData": null,
      "priceChange": null,
      "zestimate": null,
      "imgSrc": "https://photos.zillowstatic.com/fp/3fbe8cc0bcf2b803d53a861b942acad0-p_e.jpg",
      "price": 339900,
      "bedrooms": 3,
      "contingentListingType": null,
      "longitude": -122.55832,
      "latitude": 45.653374,
      "listingStatus": "FOR_SALE",
      "zpid": "23273705",
      "listingSubType": {
        "is_FSBA": true
      },
      "rentZestimate": null,
      "daysOnZillow": "8",
      "bathrooms": 3,
      "livingArea": 1584,
      "country": "USA",
      "currency": "USD",
      "lotAreaUnit": "sqft",
      "hasImage": true
    }
],
"resultsPerPage": 40,
  "totalPages": 1,
  "totalResultCount": 37,
  "schools": {},
  "currentPage": 2
}

---

**Things might need to be included in Each Property Card from API .**

1. ImgScr
2. address
3. price
4. bedrooms and bathrooms
5. living Area
6. property Type
7. listingStatus
8. zpid (-> pass to /property (Property details) and /images for detailed Info
9. lotid ( -> building detailed info)
10.  units (condos or apartments....)

![image](https://github.com/czhaoca/TheKimsPlusTwo/assets/104462860/7fded400-7ebe-41dc-a655-9f869dba0252)

**Comment by czhaoca** [comment]
The endpoint is useful regarding to data returned to use. However, please be mindful if the user put in specific address, the returned data will only include zpid.

We either need to put a logic inside our endpoint to check if this returns to zpid only, then we need to use the zpid again to gather more info from another endpoint possibly.

<img width="412" alt="Screenshot 2023-06-14 at 8 30 16 PM" src="https://github.com/czhaoca/TheKimsPlusTwo/assets/68087157/e71e598c-5d6c-43ab-ac0e-f852eb36c921">
