### ISSUE TITLE
Validate Access to Remote MongoDb Instance via mongosh

### ISSUE THREAD

**Issue by czhaoca** [czhaoca/TheKimsPlusTwo#40]
MongoDB Remote Access Validation:
Please check if you can acess the remote instance using your own machine via mongosh
[mongosh install](https://www.mongodb.com/docs/mongodb-shell/install/#std-label-mdb-shell-install)

Please use the following command to access:
mongosh --host **MONGODB_HOST** -u **MONGODB_USER** -p **MONGODB_PW**
(bold variables are stored in secrets and will be provided in a safe channel)

- [x] Christina
- [x] Elly
- [x] Ji Young
- [x] Jieun

**Comment by czhaoca** [comment]
<img width="863" alt="Screenshot 2023-06-17 at 5 34 57 PM" src="https://github.com/czhaoca/TheKimsPlusTwo/assets/68087157/664c9e51-a0b3-4d25-877e-865a9852f36e">
Please store the environment variables on local file ONLY.
@jieunkxx Please add .gitignore with *.env in your server git when it's fully provisioned. Thanks.

**Comment by chohyeonkim** [comment]
Hi ! Sorry i am not entirely sure how to access those variables? any advices would be helpful thank you ! 
![image](https://github.com/czhaoca/TheKimsPlusTwo/assets/104462860/599a42c6-72f8-4b91-b931-a8c6925dec65)

**Comment by czhaoca** [comment]
> Hi ! Sorry i am not entirely sure how to access those variables? any advices would be helpful thank you ! ![image](https://user-images.githubusercontent.com/104462860/246684710-599a42c6-72f8-4b91-b931-a8c6925dec65.png)

The secrets are posted on Notion link. The repo will automatically fetch the secrets when Github Action deploys the code base.

In our case, we may just copy the value to our local environment without putting it into Github repo. Sorry for the confusion.

**Comment by chohyeonkim** [comment]
Oh ok i found them, i will copy them on to my ,env file Thank you !

**Comment by chohyeonkim** [comment]
Sorry to bother you a lot i am trying to connect but not sure what's wrong with template
Please correct me if i am doing something wrong 

I tried other combinations too i.e) mongosh "mongodb://myUser:myPassword@example.com:27017"

MongoshInvalidInputError: [COMMON-10001] Invalid URI:

![image](https://github.com/czhaoca/TheKimsPlusTwo/assets/104462860/67c40a28-61d7-4276-8a23-b8e64c9fe62d)

**Comment by czhaoca** [comment]
> Sorry to bother you a lot i am trying to connect but not sure what's wrong with template Please correct me if i am doing something wrong
> 
> I tried other combinations too such as - mongosh "mongodb://myUser:[myPassword@example.com](mailto:myPassword@example.com):27017" ( this is just examaple)
> 
> MongoshInvalidInputError: [COMMON-10001] Invalid URI:
> 
> ![image](https://user-images.githubusercontent.com/104462860/246686112-67c40a28-61d7-4276-8a23-b8e64c9fe62d.png)

If you're in Windows environment, the command is different. You need to use mongodb://MONGODB_USER:MONGODB_PW@MONGODB_HOST:27017
to access the instance.

From my side, the service is running well.

<img width="773" alt="Screenshot 2023-06-18 at 3 43 55 PM" src="https://github.com/czhaoca/TheKimsPlusTwo/assets/68087157/faf54e94-99a7-4d74-b096-fc4f24026ed9">

**Comment by jieunkxx** [comment]
@czhaoca @chohyeonkim could you give me the link to the notion page for MongoDB? I can’t find it

**Comment by czhaoca** [comment]
> Sorry to bother you a lot i am trying to connect but not sure what's wrong with template Please correct me if i am doing something wrong
> 
> I tried other combinations too such as - mongosh "mongodb://myUser:[myPassword@example.com](mailto:myPassword@example.com):27017" ( this is just examaple)
> 
> MongoshInvalidInputError: [COMMON-10001] Invalid URI:
> 
> ![image](https://user-images.githubusercontent.com/104462860/246686112-67c40a28-61d7-4276-8a23-b8e64c9fe62d.png)

You can also run PowerShell or Command (Win + R and type cmd then Enter) using mongosh command.

**Comment by chohyeonkim** [comment]
thank you! i can access now, i will check off 

![image](https://github.com/czhaoca/TheKimsPlusTwo/assets/104462860/1756cd46-d694-4888-a063-1d54a6c6da1b)

**Comment by jieunkxx** [comment]
@chris718 please complete the task
