### ISSUE TITLE
Redux: Add Property Details from Props

### ISSUE THREAD

**Issue by chris718** [czhaoca/TheKimsPlusTwo#48]
- [x] Add Property Details data from props.

Refactor css for PropertyCard.js and PropertyGrid.js using styled-component:
- [x] Refactor PropertyCard.js
- [x] Refactor PropertyGrid.js

This change won't affect other components.

**Comment by chohyeonkim** [comment]
Hi Christina ,  please correct me if I am wrong but shouldn't be working on the likes page instead?

**Comment by chris718** [comment]
Hi Elly! yes, and it's related to #49 , we are also working on the likes page now :)

**Comment by czhaoca** [comment]
Merge completed.
