### ISSUE TITLE
Bug- components are rendered over nav bar

### ISSUE THREAD

**Issue by jieunkxx** [czhaoca/TheKimsPlusTwo#56]
### how to generate:
1. home page
2. scroll up
3. search input and property cards are rendered over the nav bar

### expected:
components are rendered under nav bar at scrolling

#### search input
![Screenshot 2023-06-22 at 12 53 33 AM](https://github.com/czhaoca/TheKimsPlusTwo/assets/67996710/51dcc825-56a2-4fb2-b7ad-035e6097e7cf)

---
<br></br>
#### property cards
![Screenshot 2023-06-22 at 12 53 44 AM](https://github.com/czhaoca/TheKimsPlusTwo/assets/67996710/9135d635-6c16-4a71-90f2-4260776d8633)

**Comment by czhaoca** [comment]
Investigate User Icon Overlay Bug
<img width="298" alt="Screenshot 2023-06-22 at 7 26 36 PM" src="https://github.com/czhaoca/TheKimsPlusTwo/assets/68087157/7f74bb2e-cc6f-43b1-9d73-4f0f131a6327">
