### ISSUE TITLE
API access request BC Assessment/MLS Data

### ISSUE THREAD

**Issue by chohyeonkim** [czhaoca/TheKimsPlusTwo#6]
https://info.bcassessment.ca/services-and-products/Pages/Data-for-Academic-Institutions.aspx

**Comment by pukkuKim** [comment]
1st e-mail sent on May 31 (Wed)

**Comment by pukkuKim** [comment]
Got a reply the next morning:

- BC Assessment's main dataset is available on Data BC’s [Data Catalogue](https://catalogue.data.gov.bc.ca/organization/bc-assessment-authority)
- Data BC can be contacted [here](https://forms.gov.bc.ca/databc-contact-us/) to initiate a request -- to be done by a supervising professor or faculty member.

**Comment by pukkuKim** [comment]
on hold (in the process of making the decision for API)

**Comment by czhaoca** [comment]
Issue closed.
