### ISSUE TITLE
Scrum 3 report

### ISSUE THREAD

**Issue by chohyeonkim** [czhaoca/TheKimsPlusTwo#80]
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?
--INCLUDE YOUR CSID IN YOUR POST--
Other Notes:
These are individual, so you are tracking your OWN work and duties
Can use this as a resource when you’re writing about your project on your resume or LinkedIn -> look back and remember details about implementation
We are having this due AFTER each workshop so that you are better able to understand the technology you’re going to be using
The real effort comes from talking to your group and planning your next steps!
Keep it short, succinct, and summarize the key points

Total: ~5 sentences max!

See Grading Rubric here: https://blogs.ubc.ca/cpsc4552023s/assessment-rubrics/#sec-2

DUE: Sunday at 10PM PT (6/25)

**Comment by chohyeonkim** [comment]
csid : w7n0n

1. During the past iteration, I worked on the Search Input/Filter Option, also I took care of minor bugs on the navigation bar and participated in the scrum meeting

2. I am not familiar with the Redux Toolkit, so currently I am trying to set it up for my search/filter input and it's a bit challenging

3. I plan to continue working on the search/filter Redux and fix bugs. We also plan to use Mapbox for our detailed page, and I will look into it as well.

**Comment by pukkuKim** [comment]
CSID: b2j9q
1. Over the past 2 weeks, I mainly worked on both the client and server sides for the user page and connected them.
2. I was struggling with understanding the code, especially WRT how different parts communicate with each other. Jieun spent hours to help me understand and fix the issues.
3. For the coming iteration, I will focus on understanding and implementing the login functionality. I will also work on calling the Zillow APIs from the backend, together with the other group members.

**Comment by chris718** [comment]
CSID: e3e4o
1. During the past sprint, I focused on connecting the back-end and front-end and also hooked up the data for properties on the detailed page.
2. It was hard to understand how the back end works since I didn't have much experience. Now I'm doing some self-learning to get stronger knowledge to do the project.
3. For the coming iteration, I plan to improve the details on the detailed page (add more functionalities/ information). Our group will create a page for comparing different properties, so I will do some research and contribute to that.

**Comment by czhaoca** [comment]
CSID: s6v0b

1. I worked on creating like button functionality and hook it up to backend using redux this sprint.
2. The difficulty comes with limited knowledge and experience with redux for me to understand complicate scenario when the redux is triggered.
3. For the upcoming sprint, I plan to implement more function to likes page. I will also contribute to Mapbox, database hookup and other upcoming issues we're going to commit.

**Comment by jieunkxx** [comment]
csid: j4n4c

1. I worked on building API flow including auth middleware, and connected backend and frontend through redux thunk to feed mock data from backend to frontend
2. This sprint needed a significant amount of updates, thereby effective project management skills were required like coordinating each member's task, tracking the progress, and supporting team members. For the coming sprints, user stories are created as small as possible to be done in a few days with acceptance criteria to better keep track of project progress. 
3. I will work on setting up external tools such as MongoDB, MapBox, and Google API in advance to further the implementation of our application.
